README.md, src/app/components/app.module.ts, src/app/components/map/legend/legend.component.html, src/app/components/map/map.component.ts, src/app/components/report/property-data/property-data.component.html, src/app/models/map-state.model.ts, src/app/models/marker-group.model.ts, src/app/models/selected-marker.model.ts, src/app/services/http.service.ts, src/assets/config.json, src/environments/environment.prod.ts, src/environments/environment.ts
Changes on the markers local storage and on the date filter
=> Changes on the markers local storage and on the date filter

src/app/components/header/header.component.html, src/app/components/header/header.component.ts, src/app/components/map/legend/legend.component.ts, src/app/components/map/map.component.ts, src/app/components/map/table/table.component.ts, src/app/components/report/deforestation-history/deforestation-history.component.html, src/app/components/report/report.component.html, src/app/components/report/report.component.ts, src/app/components/report/vision-detailed/vision-detailed.component.html, src/app/components/report/vision-detailed/vision-detailed.component.ts, src/app/components/report/vision/vision.component.html, src/app/models/property.model.ts, src/app/models/vision.model.ts, src/app/services/filter.service.ts, src/app/services/report.service.ts, src/assets/config.json
=> Changes on the report page

src/app/components/filter/filter.component.ts
Changed displayFilter to public on filter component
=> Changed displayFilter to public on filter component

package.json, src/app/components/filter/filter.component.html, src/app/components/map/table/table.component.ts, src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.ts, src/app/services/report.service.ts, tslint.json
=> Fixed production lint errors

src/app/components/map/table/table.component.ts
=> Fixed map event on the table

src/app/components/map/table/table.component.html, src/app/components/map/table/table.component.ts, src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.ts, src/app/enum/layer-type.enum.ts, src/app/services/sidebar.service.ts, src/assets/config.json
Added filter to the report table
=> Added filter to the report table

src/app/components/dashboard/dashboard.component.ts, src/app/components/filter/filter.component.ts, src/app/services/filter.service.ts, src/app/services/report.service.ts, src/assets/config.json
=> Filter for Projus

src/app/components/filter/alert-type-area/alert-type-area.component.ts, src/app/components/filter/authorization-area/authorization-area.component.html, src/app/components/filter/authorization-area/authorization-area.component.ts, src/app/components/filter/filter.component.html, src/app/components/filter/filter.component.ts, src/app/components/filter/specific-search-area/specific-search-area.component.ts, src/app/components/filter/theme-area/theme-area.component.html, src/app/components/filter/theme-area/theme-area.component.ts, src/app/components/map/map.component.ts, src/app/components/sidebar/sidebar.component.ts, src/app/models/filter-alert-type.model.ts, src/app/models/filter-authorization.model.ts, src/app/models/filter-specific-search.model.ts, src/app/models/filter-theme.model.ts, src/app/models/filter.model.ts, src/app/models/layer-filter.model.ts, src/app/models/layer.model.ts, src/app/utils/filter.utils.ts, src/assets/config.json
Creation Filter Layer
Create layers in geoserver of DETER.
Fixed errors in filter screen.
Refactored code.
=> B1.0.0 - Creation the layers of the filter.

src/assets/config.json
=> B1.0.0 - filter ok.

src/app/components/final-report/final-report.component.html, src/app/components/final-report/final-report.component.ts, src/app/components/map/map.component.ts, src/assets/config.json
=> Update view reports

package.json, src/environments/environment.prod.ts
Changed configurations for report server in clode
=> B1.0.0 - Changed configurations for report server in clode

src/app/components/final-report/final-report.component.html, src/app/components/final-report/final-report.component.ts, src/app/services/report.service.ts
Implemented the getPointsAlerts service used to generate NDVI graphics and geoserver images
=> B1.0.0 - Implemented the getPointsAlerts service used to generate NDVI graphics and geoserver images

src/app/components/filter/filter.component.ts, src/app/components/filter/specific-search-area/specific-search-area.component.html, src/app/components/filter/specific-search-area/specific-search-area.component.ts, src/app/components/final-report/final-report.component.html, src/app/components/map/map.component.ts, src/app/components/map/table/table.component.html, src/app/components/report/property-data/property-data.component.html, src/app/components/report/property-data/property-data.component.ts, src/app/components/report/report.component.html, src/app/utils/util.ts
In the definition of the document, the image of the partners, planet and new table was added. And mask in cpf/cnpj input
=> Refined DETER method and document definition.

src/app/components/final-report/final-report.component.html, src/app/components/final-report/final-report.component.ts
2. Place paragraph below the table.
3. Correction terrama2_119: MosaicSpot2008 was lost.
=> 1. Site alerts logo

src/app/components/final-report/final-report.component.ts, src/app/services/report.service.ts
Adjusting code to get prohibitivePeriod instead unauthorizedFocus.
=> Change year_occurrence to month_year_occurrence and unauthorizedFocus to prohibitivePeriod

src/app/services/report.service.ts
=> Removes barThickness from generateChart

src/app/components/map/map.component.ts
=> Fix insertion of duplicated items in legend - issue #244

src/app/components/map/map.component.ts
=> Comment an if to allow filter to rerender the map

package-lock.json, package.json
Adding  2.0.0- to version key at package.json.  
Some updates from node.
=> Adding  2.0.0- to version key at package.json

src/app/components/settings/layers/layers.component.html, src/app/components/settings/layers/layers.component.ts, src/app/services/group-view.service.ts
added method to delete all layers of the group, then add selectedGroupView values
=> added method to delete all layers of the group

src/app/components/app.module.ts, src/app/components/settings/layers/layers.component.html, src/app/components/settings/layers/layers.component.ts
checking when there is data in "selected groups" to only display the save button and display an alert that the layer has been saved successfully
=> checking when there is data in "selected groups" to only display the save button and display an alert that the layer has been saved successfully

src/app/components/settings/layers/layers.component.html
correcting if that checks when the group was selected and then displays the save button
=> correcting if that checks when the group was selected

src/app/components/final-report/final-report.component.ts
Gettiing logging map from 2006 instead last 12 years
New NDVI charts
New logo (environmental police)
new space to signature
typos and some text changes
=> B1.0.0 prodes

src/app/components/about/about.component.html
Set version to 1.0.1
Set date to 04/Março/2021
Set Copyright to 2021
=> Change version

src/app/components/final-report/final-report.component.ts
=> Fix DeforestationHistory text

src/app/components/final-report/final-report.component.ts
Removing white spaces,
Refactoring getContextDesflorestationHistory
=> Prodes report changes.

src/app/components/final-report/final-report.component.html, src/app/components/final-report/final-report.component.ts, src/app/services/export.service.ts
A new option was created to allow download report vector layers from geoserver....
=> New Feature - download report vector layers

src/app/components/final-report/final-report.component.html, src/app/components/map/table/table.component.ts
Update export rule at table and report.
=> Update export Rule
